version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-xenon
    ports:
      - 4444:4444
  firefox-node:
    image: selenium/node-firefox:3.141.59-xenon
    depends_on:
      - selenium-hub
  chrome-node:
    image: selenium/node-chrome:3.141.59-xenon
    depends_on:
      - selenium-hub
  your-app:
    build:
      context: .
    volumes:
      - .:/python-test-calculator
    depends_on:
      - firefox-node
      - chrome-node
